version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:5001/api}
        NEXT_PUBLIC_RECOMMENDATION_URL: ${NEXT_PUBLIC_RECOMMENDATION_URL:-http://localhost:5001/recommendations}
    container_name: ecommerce_frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:5001/api}
      - NEXT_PUBLIC_RECOMMENDATION_URL=${NEXT_PUBLIC_RECOMMENDATION_URL:-http://localhost:5001/recommendations}
      - NEXT_PUBLIC_APP_NAME=E-Commerce Store
      - NEXT_PUBLIC_APP_VERSION=1.0.0
    ports:
      - "3000:3000"
    networks:
      - ecommerce_network

  nginx:
    image: nginx:alpine
    container_name: ecommerce_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
    networks:
      - ecommerce_network

networks:
  ecommerce_network:
    driver: bridge
